plugins {
    id 'java'
    id 'net.neoforged.gradle.userdev' version '7.0.145'
}

version = '2.1.0'
group = 'fr.shoqapik.w2w2'

base {
    archivesName = 'xaeros_waystones_compatibility-NeoForge-1.21.1'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}


runs {
    configureEach {
        systemProperty 'forge.logging.markers', 'REGISTRIES'
        systemProperty 'forge.logging.console.level', 'debug'
        modSource project.sourceSets.main
    }

    client {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
    }

    server {
        systemProperty 'forge.enabledGameTestNamespaces', project.mod_id
        programArgument '--nogui'
    }
}

repositories {
    maven { url = 'https://www.cursemaven.com' }
}

dependencies {
    implementation "net.neoforged:neoforge:21.1.86"
    compileOnly "curse.maven:waystones-245755:5841748"
    compileOnly "curse.maven:balm-531761:5798246"
    // Xaero's Minimap 1.21.1 — sustituye el file ID con el correcto
    compileOnly "curse.maven:xaeros-minimap-263420:7598595"
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [mod_version: project.version, mod_id: project.mod_id]
    inputs.properties replaceProperties
    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
