modLoader="javafml"
loaderVersion="[2,)"
license="All rights reserved"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="Waystones2Waypoints2"
authors="Love, Cheese and small house plants"
description="Creates a Xaero's Minimap waypoint when a player activates a Waystone."

[[dependencies.w2w2]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="minecraft"
type="required"
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="waystones"
type="required"
versionRange="[0,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="xaerominimap"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
