modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"

[[mods]]
modId="w2w2"
version="${mod_version}"
displayName="Waystones2Waypoints2"
authors="Love, Cheese and small house plants"
description="Creates a Xaero's Minimap waypoint when a player activates a Waystone."

[[dependencies.w2w2]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="minecraft"
type="required"
versionRange="[26.1.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="waystones"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.w2w2]]
modId="xaerominimap"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"

[[dependencies.w2w2]]
modId="xaeroworldmap"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="CLIENT"
